from fastapi import APIRouter, Depends, HTTPException, Request
from sqlalchemy import select, update, delete
from sqlalchemy.ext.asyncio import AsyncSession
from utils.db import get_db
from models.models import Task
from uuid import UUID

router = APIRouter(prefix="/tasks", tags=["tasks"])
db: AsyncSession = Depends(get_db)

@router.get("")
async def read_tasks(db: AsyncSession = Depends(get_db)):
    # DML: Select all tasks
    result = await db.execute(select(Task))
    tasks = result.scalars().all()
    return tasks

@router.post("")
async def create_task(request: Request, db: AsyncSession = Depends(get_db)):
    data = await request.json()
    new_task = Task(**data)
    db.add(new_task) # INSERT INTO tasks (title) VALUES (...)
    await db.commit()
    await db.refresh(new_task) # Gets the ID generated by DB
    return new_task

@router.put("/{task_id}")
async def mark_complete(task_id: UUID, request: Request, db: AsyncSession = Depends(get_db)):
    try:
        # 1. Get req.body equivalent
        data = await request.json()
        # 2. Update and Return (similar to findOneAndUpdate)
        query = (
            update(Task)
            .where(Task.id == task_id)
            .values(**data)        # Unpacks dict just like req.body
            .returning(Task)       # Returns the updated row
        )
        
        result = await db.execute(query)
        updated_task = result.scalar_one_or_none()
        
        if not updated_task:
            return {"error": "Task not found"}

        await db.commit()
        return updated_task  # res.send(task)
        
    except Exception as e:
        return {"error": str(e)}


@router.delete("/{task_id}")
async def delete_task(task_id: str, db: AsyncSession = Depends(get_db)):
    try:
        # 1. Create delete query with returning (like findByIdAndDelete)
        query = (
            delete(Task)
            .where(Task.id == task_id)
            .returning(Task)
        )
        
        # 2. Execute and get the deleted record
        result = await db.execute(query)
        deleted_task = result.scalar_one_or_none()
        
        if not deleted_task:
            return {"error": "Task not found"}

        # 3. Finalize the transaction
        await db.commit()
        
        # 4. Return the deleted task (res.send(task))
        return deleted_task
        
    except Exception as e:
        return {"error": str(e)}