services:
  postgres:
    container_name: postgres-18
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=keysecret
      - POSTGRES_USER=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
  todo-backend:
    container_name: todo-backend
    build: ./backend
    ports:
      - "8881:8881"
    environment:
      - DB_HOST=host.docker.internal
      - APP_DB_USER=admin
      - APP_DB_PASSWORD=adminpass
      - APP_DB=todo_app
      - VIDEO_PATH=/app/utils/video.mp4
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./backend/video.mp4:/app/utils/video.mp4
      - ./logs/backend/app.log:/app/tlogs/app.log
    restart: always
  todo-frontend:
    container_name: todo-frontend
    build: ./frontend
    ports:
      - "3331:80"
    environment:
      - BACKEND_URL=http://host.docker.internal:8881
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    depends_on:
      - todo-backend
    volumes:
      - ./logs/frontend/:/var/log/nginx/
  fluent-bit:
    image: fluent/fluent-bit:2.2
    container_name: fluent-bit
    volumes:
      - ./logging_and_monitoring/fluent_bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./logging_and_monitoring/fluent_bit/parsers.conf:/fluent-bit/etc/parsers.conf
      - ./logging_and_monitoring/fluent_bit/extract_service.lua:/fluent-bit/etc/extract_service.lua
      - ./logs:/logs:ro
      - fluentbit-state:/fluent-bit/state
    command: [
      "fluent-bit",
      "-c", "/fluent-bit/etc/fluent-bit.conf"
    ]
    depends_on:
      - todo-frontend
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  fluentbit-state:

# networks:
#   observability:
#     external: true


# networks:
#   minikube:
#     external: true