apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: todo-app
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8881
      targetPort: 8881
      # nodePort: 32751

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: todo-app
  annotations:
    kubernetes.io/change-cause: "version 1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      nodeName: kind-cluster-control-plane
      containers:
        - name: backend
          image: todo-app-kubernetes-todo-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8881
          resources:
            requests:
              memory: "100Mi"
              cpu: "250m"
            limits:
              memory: "150Mi"
              cpu: "500m"
          env:
            # - name: MONGO_CONN_STR
            #   value: 'mongodb://admin:adminpass@mongo-svc.todo-app.svc.cluster.local:27017/?authSource=task'
            # - name: USE_DB_AUTH
            #   value: "true"
            # - name: MONGO_PASSWORD
            #   value: "adminpass"
            # - name: MONGO_USERNAME
            #   value: "admin"
            # - name: PORT
            #   value: "8080"
            - name: DB_HOST
              value: "host.docker.internal"
            - name: APP_DB_USER
              value: "admin"
            - name: APP_DB_PASSWORD
              value: "adminpass"
            - name: APP_DB
              value: "todo_app"
            - name: VIDEO_PATH
              value: "/app/utils/staticfiles/video.mp4"
          volumeMounts:
            - name: todo-storage
              mountPath: /app/utils/staticfiles
              subPath: backend/staticfiles
              readOnly: true
            - name: todo-storage
              mountPath: /app/tlogs
              subPath: logs/backend

      volumes:
        - name: todo-storage
          persistentVolumeClaim:
            claimName: todo-app-storage-pvc
        # - name: config-volume
        #   configMap:
        #     name: fluent-bit-configs
      
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - kind-cluster-control-plane
