apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: todo-app
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8881
      targetPort: 8881
      # nodePort: 32751

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: todo-app
  annotations:
    kubernetes.io/change-cause: "version 1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      nodeName: kind-cluster-control-plane
      containers:
        - name: backend
          image: todo-app-kubernetes-todo-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8881
          resources:
            requests:
              memory: "100Mi"
              cpu: "250m"
            limits:
              memory: "150Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8881
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8881
            periodSeconds: 10
            timeoutSeconds: 5
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          volumeMounts:
            - name: todo-storage
              mountPath: /app/utils/staticfiles
              subPath: backend/staticfiles
              readOnly: true
            - name: todo-storage
              mountPath: /app/tlogs
              subPath: logs/backend

      volumes:
        - name: todo-storage
          persistentVolumeClaim:
            claimName: todo-app-storage-pvc
        # - name: config-volume
        #   configMap:
        #     name: fluent-bit-configs
      
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - kind-cluster-control-plane

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: todo-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
