apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: todo-app
data:
  # MONGO_CONN_STR: 'mongodb://admin:adminpass@mongo-svc.todo-app.svc.cluster.local:27017/?authSource=task'
  # USE_DB_AUTH: "true"
  # MONGO_PASSWORD: "adminpass"
  # MONGO_USERNAME: "admin"
  # PORT: "8080"
  DB_HOST: "host.docker.internal"
  APP_DB_USER: "admin"
  APP_DB: "todo_app"
  VIDEO_PATH: "/app/utils/staticfiles/video.mp4"
  BACKEND_URL: "http://backend-svc.todo-app:8881"

---

apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: todo-app
type: Opaque
data:
  APP_DB_PASSWORD: YWRtaW5wYXNz