apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: todo-app
spec:
  selector:
    app: mongo
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      # nodePort: 32017

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
        namespace: todo-app
    spec:
      nodeSelector:
        kubernetes.io/hostname: minikube
      containers:
      - name: mongo
        image: bitnami/mongodb:latest
        ports:
          - containerPort: 27017
        env:
          - name: MONGODB_ROOT_PASSWORD
            value: "keysecret"
          - name: MONGODB_USERNAME
            value: "admin"
          - name: MONGODB_PASSWORD
            value: "adminpass"
          - name: MONGODB_DATABASE
            value: "task"
        # volumeMounts:
        #   - name: mongo-volume
        #     mountPath: /bitnami/mongodb
      volumes:
        - name: mongo-volume
          # emptyDir: {} # For temp dir volume which persists data until pod lives.
          # hostPath: # For host or node dir volume which persists data until node lives.
          #   path: /data
          persistentVolumeClaim:
            claimName: mongo-pvc
