apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: todo-app
spec:
  selector:
    app: mongo
  type: NodePort
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 32017

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: bitnami/mongodb:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGODB_ROOT_PASSWORD
              value: "keysecret"
            - name: MONGODB_USERNAME
              value: "admin"
            - name: MONGODB_PASSWORD
              value: "adminpass"
            - name: MONGODB_DATABASE
              value: "task"