apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: todo-app
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: /media/homepc/FILES/lavan-practice/Todo-App-Kubernetes/persistent-stores/mongo-vol
  nodeAffinity: # Ensures the scheduler knows where this PV lives
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube 

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: todo-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  storageClassName: manual