apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-app-storage-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
      path: /todo_storage

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-app-storage-pvc
  namespace: todo-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: todo-app-storage-pv
  storageClassName: manual