name: Build Test and Release
run-name: ${{ github.actor }} is starting the build action.
on:
  push:
    branches:
    - '**'

permissions:
  contents: read
  packages: write
env:
  MAJOR_VERSION: 1
  REGISTRY: ghcr.io
  COMPONENT: todo-app

jobs:
  build_and_test:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: build and test
      run: |
        echo "Building and testing the project..."
        # 1. Assign to local shell variables
        # This makes them available IMMEDIATELY in this run block
        BUILD_NUMBER="${{ env.MAJOR_VERSION }}.${{ github.run_number }}"
        FRONTEND_IMAGE_TAG="${{ env.REGISTRY }}/${{ env.COMPONENT }}/frontend:$BUILD_NUMBER"
        BACKEND_IMAGE_TAG="${{ env.REGISTRY }}/${{ env.COMPONENT }}/backend:$BUILD_NUMBER"

        # 2. Export them for the current shell session
        # Now any scripts called in this block can see these variables
        export FRONTEND_IMAGE_TAG
        export BACKEND_IMAGE_TAG

        # 3. Persist for FUTURE steps
        echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV
        echo "FRONTEND_IMAGE_TAG=$FRONTEND_IMAGE_TAG" >> $GITHUB_ENV
        echo "BACKEND_IMAGE_TAG=$BACKEND_IMAGE_TAG" >> $GITHUB_ENV

        ./scripts/build.sh build_containers
        ./scripts/build.sh test_containers

    - name: Log in to the Container registry only if publish-image branch
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push container images
      if: github.ref == 'refs/heads/main'
      run: |
        docker push $FRONTEND_IMAGE_TAG
        docker push $BACKEND_IMAGE_TAG
        echo "Containers pushed successfully!"
